name: "fabric-network"
version: "1.0.0"
client:
  organization: Org1
organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
